grade-scores: CSimpleCSV Class Reference
CSimpleCSV Class Reference
#include <process.h>
Public Member Functions
CSimpleCSV ()
e_rwcode read (const char *filename)
unsigned int records ()
void sort ()
void print ()
e_rwcode save (const char *filename)
CSimpleCSV (const CSimpleCSV &)
CSimpleCSV & operator= (const CSimpleCSV &)
Detailed Description
Simple composite class for reading a CSV file. Note that this class cannot handle and is not intended to handle complex CSV files. If the data row does not match exact specification an error message is shown and the row will be discarded. The read of the file expects a perfectly formatted line and the strings cannot contain internal commas or any escaped CSV formatting. Line format: LastName, FirstName, Score Field types must be: string, string, int Data lines that don't match expected format are rejected.
Definition at line 150 of file process.h.
Constructor & Destructor Documentation
CSimpleCSV() [1/2]
CSimpleCSV::CSimpleCSV () inline
Constructor
Definition at line 194 of file process.h.
CSimpleCSV() [2/2]
CSimpleCSV::CSimpleCSV (const CSimpleCSV &) inline
Copy constructor, intentionally not implemented
Definition at line 231 of file process.h.
Member Function Documentation
operator=()
CSimpleCSV& CSimpleCSV::operator= (const CSimpleCSV &) inline
Copy assignment operator, intentionally not implemented
Definition at line 236 of file process.h.
print()
void CSimpleCSV::print () inline
Print the contents of stored records to console
Definition at line 215 of file process.h.
Referenced by main().
read()
e_rwcode CSimpleCSV::read (const char * filename)
Read and store contents of CSV file
Parameters
[in] filename Name of CSV file to read
Returns
TRUE upon successful read of all data, FALSE otherwise
Definition at line 219 of file process.cpp.
Referenced by main(), TESTCASE(), and TESTCASE_WITH_DATA().
records()
unsigned int CSimpleCSV::records () inline
Numer of available records
Returns
Number of available records read in from CSV file
Definition at line 205 of file process.h.
Referenced by main(), and TESTCASE().
save()
e_rwcode CSimpleCSV::save (const char * filename)
Save data stored in m_records to specified filename
Parameters
[in] filename Destination file name for data
Definition at line 257 of file process.cpp.
Referenced by main().
sort()
void CSimpleCSV::sort ()
Sort the vector Orders the names by their score. If scores are the same, order by their last name followed by first name.
Definition at line 252 of file process.cpp.
Referenced by main(), and TESTCASE_WITH_DATA().
The documentation for this class was generated from the following files:
process.h
process.cpp