grade-scores: grade-scores.cpp File Reference
grade-scores.cpp File Reference
#include "process.h"
Functions
int main (int argc, char **argv)
Detailed Description
This file contains the implementation of grade-scores.exe application.
Version
Definition in file grade-scores.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Application entry point. This application requires exactly one command line parameter which must be a valid text file for sorting.
Parameters
[in] argc Number of command line arguments
[in] argv Array of command line arguments
Returns
EXIT_OK upon success, EXIT_FAIL otherwise
Definition at line 50 of file grade-scores.cpp.
References CSimpleCSV::print(), CSimpleCSV::read(), CSimpleCSV::records(), CSimpleCSV::save(), and CSimpleCSV::sort().