grade-scores: unittest.cpp File Reference
unittest.cpp File Reference
#include "process.h"
#include "testcase.h"
Macros
#define ARGC 2
Number of command line parameters that are required.
Enumerations
enum e_sort_action { SORT_INIT = 0, SORT_SORT, SORT_TEST, SORT_CLEAN }
Functions
TESTCASE_WITH_DATA (Filenames_01, int argc;const char *argv1;const char *outName;)
TESTCASE_POPULATE_DATA (Filenames_01)
TESTCASE_POPULATE_DATA_END TESTCASE (Filenames_02)
TESTCASE (Filenames_03)
TESTCASE_WITH_DATA (Sort_01, const char *last;const char *first;unsigned long long score;e_sort_action action;)
TESTCASE_POPULATE_DATA_END int main (int argc, char **argv)
Detailed Description
This file contains the implementation of grade-scores.exe application.
Version
Definition in file unittest.cpp.
Enumeration Type Documentation
e_sort_action
enum e_sort_action
Helper for state of sort testing
Enumerator
SORT_INIT
Pre test, initialise.
SORT_SORT
Pre test, sort data and initialise row counter.
SORT_TEST
No pre/post actions.
SORT_CLEAN
Post test, clean up.
Definition at line 24 of file unittest.cpp.
Function Documentation
main()
TESTCASE_POPULATE_DATA_END int main (int argc, char ** argv)
Application entry point. This application requires no command line parameters. Normally we would use something like cppunit but this is just a quick test to show unit tests can be written and CI can execute them
Parameters
[in] argc Number of command line arguments
[in] argv Array of command line arguments
Returns
EXIT_OK upon success, EXIT_FAIL otherwise
Definition at line 274 of file unittest.cpp.
TESTCASE() [1/2]
TESTCASE_POPULATE_DATA_END TESTCASE (Filenames_02)
Test case will be testing: . Passing a non existent filename to validate_arg() . Confirming the return is false . Confirming global destination filename is unset
Definition at line 111 of file unittest.cpp.
References ARGC.
TESTCASE() [2/2]
TESTCASE (Filenames_03)
Test case will be testing: . Test a file with formatting issues can be read and processed . Lines with format issues will be discarded Additional notes. The file name will be tested must exist under the "testdata/" folder.
Definition at line 134 of file unittest.cpp.
References ARGC, CSimpleCSV::read(), and CSimpleCSV::records().
TESTCASE_POPULATE_DATA()
TESTCASE_POPULATE_DATA (Filenames_01)
Data for test case Filenames_01
Definition at line 61 of file unittest.cpp.
References ARGC.
Referenced by TESTCASE_WITH_DATA().
TESTCASE_WITH_DATA() [1/2]
TESTCASE_WITH_DATA (Filenames_01 , int argc;const char *argv1;const char *outName;)
Test case will be testing: . Return code from validate_arg() is always true . The output file names have been correctly constructed Additional notes. The file names which are tested must also exist under the "testdata/" folder.
Definition at line 41 of file unittest.cpp.
TESTCASE_WITH_DATA() [2/2]
TESTCASE_WITH_DATA (Sort_01 , const char *last;const char *first;unsigned long long score;e_sort_action action;)
Test case will be testing: . Veify the source data has not been changed . Verify the sorted result is per specification Additional notes. The file name will be tested must exist under the "testdata/" folder.
Definition at line 160 of file unittest.cpp.
References CSimpleCSV::read(), CSimpleCSV::sort(), SORT_CLEAN, SORT_INIT, SORT_SORT, SORT_TEST, and TESTCASE_POPULATE_DATA().